# 1. ConfigMap: Chuyển toàn bộ biến môi trường từ Docker Compose vào đây
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  # --- Identity & Roles ---
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"  
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  
  # --- Networking ---
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-0.kafka-service.kafka.svc.cluster.local:9093"
  
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
  
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka-service.kafka.svc.cluster.local:9092"
  
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  
  # --- Internal & Storage ---
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"

---
# 2. Service Headless (Không thay đổi)
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: plaintext
  - port: 9093
    name: controller
  clusterIP: None
  selector:
    app: kafka

---
# 3. StatefulSet 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.8.3  
        ports:
        - containerPort: 9092
        - containerPort: 9093
        envFrom:
        - configMapRef:
            name: kafka-config
       
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi