apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.8.3
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 9093
          name: controller
        env:
        # --- CẤU HÌNH KRAFT ---
        # 1. Cluster ID (Bắt buộc phải là Base64 UUID hợp lệ)
        - name: CLUSTER_ID
          value: "MkU3OEVBNTcwNTJENDM2Qk"
          
        - name: KAFKA_NODE_ID
          value: "1"
          
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
          
        # 2. Sửa voters thành localhost để tự giao tiếp nội bộ ổn định
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

        # 3. Advertised Listeners trỏ ra Service Kubernetes
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
        
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
          
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"